language: php

php:
  - 5.0
    dist: precise
  - 5.1
    dist: precise
  - 5.3
    dist: precise
  - 5.4
    dist: precise
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm-3.3
    dist: trusty
  - hhvm-3.6
    dist: trusty
  - hhvm-3.9
    dist: trusty
  - hhvm-3.12
    dist: trusty
  - hhvm-3.15
    dist: trusty
  - hhvm-3.24
    dist: trusty
  
script: |
  composer install --optimize-autoloader --no-suggest --no-dev
  phpunit
