language: php

matrix:
  include:
    - php: 5.0
      dist: precise
    - php: 5.1
      dist: precise
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
      dist: precise
    - php: 7.0
      dist: trusty
    - php: 7.1
      dist: trusty
    - php: 7.2
      dist: trusty
    - php: hhvm-3.3 
      dist: trusty
      sudo: required
    - php: hhvm-3.6 
      dist: trusty
      sudo: required
    - php: hhvm-3.9 
      dist: trusty
      sudo: required
    - php: hhvm-3.12 
      dist: trusty
      sudo: required
    - php: hhvm-3.15 
      dist: trusty
      sudo: required
    - php: hhvm-3.24 
      dist: trusty
      sudo: required
  
script: |
  composer install --optimize-autoloader --no-suggest --no-dev
  phpunit
